<a href="https://colab.research.google.com/github/fathanick/Python-basic/blob/master/01_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

Numpy stands for *numerical Python*, a Python library that focuses on scientific computing.

###Why Numpy?


*   It provides an efficient interface to store and operate on dense data buffers
*   NumPy arrays are like Python’s built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.

###Arrays

In [0]:
import numpy as np

In [17]:
a = np.array([1, 2, 3, 4, 5])   # Create a rank 1 array
print(a)                        # Prints [1 2 3 4 5]
print(type(a))                  # Prints "<class 'numpy.ndarray'>"

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
print(a.shape)            # Prints "(5,)"

(5,)


In [7]:
print(a[0], a[1], a[2])   # Prints "1 2 3"

1 2 3


In [14]:
a[0] = 7                  # Change an element of the array. In this example, we change the first element (index=0) 
print(a)                  # Prints "[7, 2, 3, 4, 5]"

[7 2 3 4 5]


In [18]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b)                           # Prints "[[1 2 3]
                                   #          [4 5 6]]"
                              
print(b.shape)                     # Prints "(2, 3)"

[[1 2 3]
 [4 5 6]]
(2, 3)


* Remember that unlike Python lists, NumPy is constrained to arrays that all 
contain the **same type**. 
* If types do not match, NumPy will **upcast** if possible (here, integers are
upcast to floating point):

In [68]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

###Functions to Create Arrays

In [30]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[0. 0.]
 [0. 0.]]


In [20]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

[[1. 1.]]


In [23]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[7 7]
 [7 7]]


In [24]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[1. 0.]
 [0. 1.]]


In [27]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     

[[0.86569396 0.10120034]
 [0.5192007  0.0132109 ]]


In [28]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
# Create an array of five values evenly spaced between 0 and 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal(0, 1, (3, 3))

array([[-1.61088142,  2.01999756,  0.50916041],
       [-1.48113585,  0.57111568,  0.68480427],
       [ 0.74571361,  0.41754881, -0.11485848]])

In [37]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[4, 4, 3],
       [9, 1, 5],
       [5, 9, 0]])

In [38]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([2.5e-323, 9.9e-324, 1.5e-323])

###NumPy Array Attributes

In [0]:
np.random.seed(0) # seed for reproducibility

a1 = np.random.randint(10, size=6) # One-dimensional array
a2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
a3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

Each array has attributes **ndim** (the number of dimensions), **shape** (the size of each dimension), and **size** (the total size of the array):

In [67]:
print("a3 ndim: ", a3.ndim)
print("a3 shape:", a3.shape)
print("a3 size: ", a3.size)

a3 ndim:  3
a3 shape: (3, 4, 5)
a3 size:  60


### NumPy Standard Data Types

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that we can use to construct arrays. Numpy tries to guess a datatype when we create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

Below are the standard NumPy data types

![alt text](https://miro.medium.com/max/1378/0*kuKgrAsZQ8D_hzjD.png)


In [69]:
# Check data type or array

a3.dtype

dtype('int64')

In creating an array, we can specify a data type by adding the **dtype parameter**.

In [70]:
arr = np.array([1, 4, 2, 5, 3], dtype='int32')
arr.dtype

dtype('int32')

###Array indexing: Accessing Single Elements

In [44]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [45]:
# In a one-dimensional array, we can access the ith value (counting from zero) by specifying the desired index in square brackets, just as with Python lists:

print(arr[3])
print(arr[0])

4
1


In [46]:
# Use negative indices, to index from the end of the array

print(arr[-3])
print(arr[-2])

3
4


In [62]:
# In a multidimensional array, we access items using a comma-separated tuple of indices

arr2 = np.array([[1, 2, 3, 4],
                 [7, 6, 8, 5],
                 [12, 11, 10, 9]])
print(arr2)
print(arr2[0,0]) # Print item in the first row and first column
print(arr2[1,2]) # Print item in the second row and third column
print(arr2[2,-3]) # Print item in the third row and third column from the end

[[ 1  2  3  4]
 [ 7  6  8  5]
 [12 11 10  9]]
1
8
11


In [64]:
# We can also modify values using any of the above index notation

arr2[0,1] = 19
print(arr2)

[[ 1 19  3  4]
 [ 7  6 19  5]
 [12 11 10  9]]


###Array Slicing: Accessing Subarrays

The NumPy slicing syntax follows that of the standard Python list; to access a slice of
an array x, use this:


---


***x[start:stop:step]***


---


If any of these are unspecified, they default to the values *start=0*, *stop=size of
dimension*, *step=1*. 

####One-dimensional subarrays

In [71]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [73]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [74]:
x[4:7] # middle subarray

array([4, 5, 6])

In [75]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [76]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [77]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [78]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

####Multidimensional subarrays

In [79]:
a2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [80]:
a2[:2, :3] # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [81]:
a2[:3, ::2] # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [82]:
# Subarray dimensions can even be reversed together

a2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

####Accessing Array Rows and Columns

In [83]:
print(a2[:, 0]) # first column of x2

[3 7 1]


In [84]:
print(a2[0]) # equivalent to a2[0, :]

[3 5 2 4]


###Reshaping of Arrays

In [90]:
# The most flexible way of doing this is with the reshape() method

grid = np.arange(1,10)
print("Before: ",grid)
new_grid = grid.reshape(3,3) # Reshape grid to 3x3
print("After: ")
print(new_grid)

Before:  [1 2 3 4 5 6 7 8 9]
After: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [93]:
# row vector via reshape
x = np.array([1, 2, 3])
print(x)
print(x.reshape((1, 3)))

[1 2 3]
[[1 2 3]]


In [97]:
# row vector via newaxis
print(x[np.newaxis, :])

array([[1, 2, 3]])

In [95]:
# column vector via reshape
print(x.reshape((3, 1)))

[[1]
 [2]
 [3]]


In [98]:
# column vector via newaxis
print(x[:, np.newaxis])

[[1]
 [2]
 [3]]


###Array Concatenation and Splitting

####Concatenation of arrays

In [99]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [101]:
# concatenate along the first axis
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [102]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the **np.vstack(vertical stack)** and **np.hstack (horizontal stack)** functions.

In [103]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [104]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

####Splitting of Arrays

The opposite of concatenation is splitting, which is implemented by the functions **np.split**, **np.hsplit**, and np.vsplit.

In [105]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [106]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [108]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


###References


*   https://cs231n.github.io/python-numpy-tutorial/
*   https://medium.com/@yasirabd/pengenalan-numpy-pandas-matplotlib-b90bafd36c0
* Python Data Science Handbook

